[tool.poetry]
name = "neural-networks-project"
version = "0.1.0"
description = ""
authors = ["lef8"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
